# Makefile for compiling MPQKit
#
# Author : Xavier Glattard <xavier.glattard@online.fr>
# Created: Tue Oct 02 2007

ADDITIONAL_CFLAGS = -Wno-unknown-pragmas -std=gnu99
ADDITIONAL_CCFLAGS = -Wno-unknown-pragmas
ADDITIONAL_OBJCFLAGS = -Wno-unknown-pragmas -std=gnu99
