# Makefile for compiling MPQKit
#
# Author : Xavier Glattard <xavier.glattard@online.fr>
# Created: Tue Oct 02 2007

include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = wave

wave_INCLUDE_DIRS = -I. -I.. -I../..

wave_C_FILES = \
	wave.c \

-include Makefile.preamble
include $(GNUSTEP_MAKEFILES)/subproject.make
-include Makefile.postamble
